# Site settings
title: Elias Esmaeilzadeh
description: Contact Me
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Elias<br>Esmaeilzadeh
user_description: I'm a student of Biology at FUM university, studying Neuroscience & also a nomad Web Developer. you can contact me via links below my name.
user_title: Undergraduate Biology Student
email: EliasEsmaeilzadeh@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
